La idea de esta práctica es ejercitar los puntos que vamos a necesitar para resolver el desafío.

Usaremos un resumen del dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data


## Ejercicio 1
Leer los datos del archivo /M1/CLASE_03_Numpy/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [4]:
import numpy as np

# local:
data_location = 'Data/sales_data_sample_excercise.csv'


In [17]:
data = np.genfromtxt(data_location, skip_header=1 , delimiter='\t' , dtype='str')
data.shape

(2823, 6)

In [9]:
np.genfromtxt(data_location, skip_header=1 , delimiter='\t' , dtype='int')

array([[10107,  2871,     2,  2003,    -1,    -1],
       [10121,  2765,     5,  2003,    -1,    -1],
       [10134,  3884,     7,  2003,    -1,    -1],
       ...,
       [10386,  5417,     3,  2005,    -1,    -1],
       [10397,  2116,     3,  2005,    -1,    -1],
       [10414,  3079,     5,  2005,    -1,    -1]])

Al crear el array como int, convierte todos los datos a int, reemplazando por ejemplo los textos por "-1"

# Ejercicio 2 - Tipos

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [19]:
sales = data[:,1].astype(float)
country = data[:,5]

In [36]:
print(sales)
print(country)

[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]
['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


## Ejercicio 3 - Funciones de agregación

Sobre los datos de precios de ventas (columna SALES) calcular:

* mínimo

* máximo

* promedio

* cantidad

* suma

Ayuda: https://docs.scipy.org/doc/numpy-1.17.0/reference/routines.statistics.html

In [28]:
print(f'Mínimo: {np.min(sales)}')
print(f'Máximo: {np.max(sales)}')
print(f'Promedio: {np.average(sales)}')
print(f'Cantidad: {sales.shape[0]}')
print(f'Suma: ${np.sum(sales):.0f}')

Mínimo: 482.13
Máximo: 14082.8
Promedio: 3553.889071909316
Cantidad: 2823
Suma: $10032629


## Ejercicio 4 - Indexing

a) ¿Cuántas ventas se hicieron en USA?

Ayuda: boolean indexing

b) ¿Cuáles son los precios de las 5 ventas que están en las filas 6 a 10 del dataset?

Resolvamos usando array slicing y fancy indexing

Ayuda: recuerden `range` https://docs.python.org/3/library/functions.html#func-range

In [31]:
# a)
sales[country == 'USA'].shape[0]

1004

In [32]:
# b)
sales[6:11]

array([2497.77, 5512.32, 2168.54, 4708.44, 3965.66])

In [42]:
rango = range(6,11)
sales[rango]

array([2497.77, 5512.32, 2168.54, 4708.44, 3965.66])